bitprice/urls.py
from django.conf.urls import url

from . import views

app_name = 'bitprice'

urlpatterns = [
	url(r'^$', views.home, name='home'),
	url(r'^monthly-records/(\w+)/$', views.monthly_records, name='monthly-records'),
]

weather/urls.py
from django.conf.urls import url
from . import views

app_name = 'weather'

urlpatterns = [
	url(r'^$', views.home, name='home'),
]

weatherapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('weather.urls', namespace='weather'), name='weather'),
    url(r'^bitprice/', include('bitprice.urls', namespace='bitprice'), name='bitprice')
]

bitprice/models.py
from django.db import models

# Create your models here.
class BitcoinPrice(models.Model):
	update_date = models.CharField(max_length=100)
	kes = models.FloatField()
	usd = models.FloatField()
	time_added = models.DateTimeField()

	def __str__(self):
		return self.update_date

weather/models.py
from django.db import models

# Create your models here.
class Reading(models.Model):
	location = models.CharField(max_length=100)
	weather = models.CharField(max_length=50)
	wind_str = models.CharField(max_length=100)
	temp = models.IntegerField()
	humidity = models.CharField(max_length=10)
	precip = models.CharField(max_length=50)
	icon_url = models.TextField()
	observation_time = models.CharField(max_length=100)

	def __str__(self):
		return self.location

bitprice/views.py
from django.core.paginator import Paginator
from django.db.models import Avg, Min, Max
from django.shortcuts import render
from .models import BitcoinPrice
import datetime, calendar

# Create your views here.
def home(request):
	leo = datetime.date.today()
	today = datetime.datetime.now()
	mwaka = today.year

	months_choices = []
	for i in range(1,13):
	    months_choices.append((i, datetime.date(mwaka, i, 1).strftime('%B')))

	price_list = BitcoinPrice.objects.filter(time_added__year=leo.year, time_added__month=leo.month).order_by('-time_added')
	price_graph = BitcoinPrice.objects.filter(time_added__year=leo.year, time_added__month=leo.month).extra(select={'day': 'date(time_added)'}).values('day').annotate(top_price=Max('usd'), low_price = Min('usd'))
	price_range = BitcoinPrice.objects.filter(time_added__year=leo.year, time_added__month=leo.month).aggregate(max_price = Max('usd'), min_price = Min('usd'))

	page = request.GET.get('page', 1)

	paginator = Paginator(price_list, 15)

	try:
		prices = paginator.page(page)
	except PageNotAnInteger:
		prices = paginator.page(1)
	except EmptyPage:
		prices = paginator.page(paginator.num_pages)



	context = {
		'months_choices' : months_choices,
		'prices' : prices,
		'price_graph' : price_graph,
		'price_range' : price_range,
	}
	return render(request, 'bitprice/index.html', context)



# Query by month
def monthly_records(request, month):
	today = datetime.datetime.now()
	mwaka = today.year
	if not month:
		month = today.month

	months_choices = []
	for i in range(1,13):
	    months_choices.append((i, datetime.date(mwaka, i, 1).strftime('%B')))


	price_list = BitcoinPrice.objects.filter(time_added__year=mwaka, time_added__month=month).order_by('-time_added')
	price_graph = BitcoinPrice.objects.filter(time_added__year=mwaka, time_added__month=month).extra(select={'day': 'date(time_added)'}).values('day').annotate(top_price=Max('usd'), low_price = Min('usd'))
	price_range = BitcoinPrice.objects.filter(time_added__year=mwaka, time_added__month=month).aggregate(max_price = Max('usd'), min_price = Min('usd'))
	query_month = calendar.month_name[int(month)]

	page = request.GET.get('page', 1)

	paginator = Paginator(price_list, 15)

	try:
		prices = paginator.page(page)
	except PageNotAnInteger:
		prices = paginator.page(1)
	except EmptyPage:
		prices = paginator.page(paginator.num_pages)



	context = {
		'months_choices' : months_choices,
		'prices' : prices,
		'price_graph' : price_graph,
		'price_range' : price_range,
		'query_month' : query_month,
	}
	return render(request, 'bitprice/index.html', context)

weather/views.py
from django.shortcuts import render
from .models import Reading

# Create your views here.
def home(request):
	data = Reading.objects.last()
	temp = data.temp
	# convert to degrees celsius
	temp_celsius = (temp-32)/1.8
	context = {
		'data' : data,
		'temp_celsius' : temp_celsius,
	}

	return render(request, 'weather/index.html', context)

bitprice/templates/bitprice/index.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}BitPrice - Home{% endblock %}

{% block content %}
<div class="row">
	<div class="page-header">
		<div class="dropdown pull-right">
		  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Query by month
		  <span class="caret"></span></button>
		  <ul class="dropdown-menu">
		    {% for month in months_choices %}
			<li><a class="dropdown-item" href="{% url 'bitprice:monthly-records' month.0 %}">{{ month.1 }}</a></li>
			{% endfor %}
		  </ul>
		</div>
		<h1>{% if query_month %} {{ query_month }} {% else %} {% now "F" %} {% endif %} Bitcoin Price Index</h1>
	</div>
	<div id="bit-price-data" class="table-responsive">
		<h3>Top price: <span class="top-price">${{ price_range.max_price | floatformat:2 | intcomma }}</span></h3>
		<h3>Low price: <span class="low-price">${{ price_range.min_price | floatformat:2 | intcomma }}</span></h3>
		<table class="table table-striped">
			<thead>
				<th>Update time</th>
				<th>Time added</th>
				<th>Kenya Shilling</th>
				<th>US Dollar</th>
			</thead>
			<tbody>
				{% if prices %}
				{% for price in prices %}
				<tr>
					<td>{{ price.update_date }}</td>
					<td>{{ price.time_added }}</td>
					<td>ksh.{{ price.kes|floatformat:2|intcomma }}</td>
					<td>${{ price.usd|intcomma }}</td>
				</tr>
				{% endfor %}
				{% endif %}
			</tbody>
		</table>
		<nav class="col-md-offset-4">
			{% if prices.has_other_pages %}
			  <ul class="pagination">
			    {% if prices.has_previous %}
			      <li><a href="?page={{ prices.previous_page_number }}">&laquo;</a></li>
			    {% else %}
			      <li class="disabled"><span>&laquo;</span></li>
			    {% endif %}
			    {% for i in prices.paginator.page_range %}
			      {% if prices.number == i %}
			        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
			      {% else %}
			        <li><a href="?page={{ i }}">{{ i }}</a></li>
			      {% endif %}
			    {% endfor %}
			    {% if prices.has_next %}
			      <li><a href="?page={{ prices.next_page_number }}">&raquo;</a></li>
			    {% else %}
			      <li class="disabled"><span>&raquo;</span></li>
			    {% endif %}
			  </ul>
			{% endif %}
		</nav>
	</div>
</div>
<div class="row">
	<div class="page-header">
		<h2>Bitcoin Price Trend Graphical Representation</h2>
	</div>
	<div id="pricechart" class="bit-price-graph"></div>
</div>
{% endblock %}

templates/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- <meta http-equiv="Refresh" Content="5"> -->
    <link rel="icon" href="favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <!-- Morris graph -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
  </head>

  <body>

    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="{% url 'weather:home' %}" class="navbar-brand">BitWay App</a>
      </div>
      <div class="collapse navbar-collapse" id="topNavBar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'bitprice:home' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span> Bitprice</a></li>
          <li><a href="{% url 'weather:home' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span> Weather</a></li>
        </ul>
        <form class="navbar-form navbar-left" role="search" method="get" action="#">
          <div class="form-group">
            <input type="text" name="query" class="form-control" value="">
          </div>
          <button type="submit" class="btn btn-default">Search</button>
        </form>
        <!-- <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Album</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Profile</a></li>
        </ul> -->
      </div>
      
    </div>
  </nav>

    <div class="container">

      {% block content %}
      {% endblock %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Morris graph -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

    <script type="text/javascript">
      new Morris.Bar({
        // ID of the element in which to draw the chart.
        element: 'pricechart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: [
        {% for pricing in price_graph %}
          { day: '{{ pricing.day }}', max: {{ pricing.top_price|floatformat:1 }}, min: {{ pricing.low_price|floatformat:1 }} },
        {% endfor %}
        ],
        // The name of the data record attribute that contains x-values.
        xkey: 'day',
        // A list of names of data record attributes that contain y-values.
        ykeys: ['max', 'min'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['Max', 'Min'],
        barColors: ['green', '#eca14f'],
        xLabelAngle: 45
      });
    </script>

    <!-- <script type="text/javascript">
      function refresh() {
          $.ajax({
              url: '{% url "bitprice:home" %}',
              success: function(data) {
                  $('#bit-price-data').html(data);
                  setInterval(refresh, 50000);
              }
          });
      }

      $(function(){
          refresh();
      });
    </script> -->

  </body>
</html>

weather/templates/weather/index.html
{% extends "base.html" %}
{% load humanize %}

{% block title %} Home {% endblock %}

{% block content %}
<div class="row">
	<h2 class="page-header text-center">Weather Station</h2>
	<div class="col-md-offset-4">
		<ul class="list-unstyled">
			{% if data %}
			<li><img src="{{ data.icon_url }}"></li>
			<li>Location : {{ data.location }}</li>
			<li>Currently : {{ data.weather }}</li>
			<li>Wind : {{ data.wind_str }}</li>
			<li>Temp : {{ temp_celsius|floatformat:1 }}˚C</li>
			<li>Humidity : {{ data.humidity }}</li>
			<li>Precipitation : {{ data.precip }}</li>
			<li>{{ data.observation_time }}</li>
			{% endif %}
		</ul>
	</div>
</div>
{% endblock %}